language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
install:
 - pip install -r requirements.txt --use-mirrors
 - pip install coverage nose --use-mirrors
 - pip install -e .
script: nosetests --config=nose.cfg
after_success:
 - pip install coveralls
 - coveralls
